const grammarQuizData = [
    // --- 1. Be動詞 (現在) ---
    { category: "Be動詞 (現在)", ja: "私はエドワード・トラウトです。", en: "I am Edward Trout." },
    { category: "Be動詞 (現在)", ja: "彼女は私たちの新しい先生です。", en: "She is our new teacher." },
    { category: "Be動詞 (現在)", ja: "こちらは純です。", en: "This is Jun." },
    { category: "Be動詞 (現在)", ja: "彼らは良い友達です。", en: "They are good friends." },
    { category: "Be動詞 (現在)", ja: "私たちはテストの準備ができています。", en: "We are ready for the test." },
    { category: "Be動詞 (現在)", ja: "その本はとても興味深いです。", en: "The book is very interesting." },
    { category: "Be動詞 (現在)", ja: "東京は日本の首都です。", en: "Tokyo is the capital of Japan." },
    { category: "Be動詞 (現在)", ja: "今日は空が青いです。", en: "The sky is blue today." },
    { category: "Be動詞 (現在)", ja: "私はアニメのファンではありません。", en: "I am not an anime fan." },
    { category: "Be動詞 (現在)", ja: "彼は1年2組ではありません。", en: "He is not in Class 1-2." },
    { category: "Be動詞 (現在)", ja: "彼らは今ここにいません。", en: "They are not here now." },
    { category: "Be動詞 (現在)", ja: "あなたはアニメのファンですか。", en: "Are you an anime fan?" },
    { category: "Be動詞 (現在)", ja: "彼はサッカー部に入っていますか。", en: "Is he on the soccer team?" },
    { category: "Be動詞 (現在)", ja: "彼らはその結果に満足していますか。", en: "Are they happy with the result?" },
    { category: "Be動詞 (現在)", ja: "はい、そうです。", en: "Yes, I am." },
    { category: "Be動詞 (現在)", ja: "いいえ、ちがいます。", en: "No, they are not." },

    // --- 2. 一般動詞 (現在) ---
    { category: "一般動詞 (現在)", ja: "私は日本の甘い菓子が好きです。", en: "I like Japanese sweets." },
    { category: "一般動詞 (現在)", ja: "私は大福とあんみつが大好きです。", en: "I love daifuku and ammitsu." },
    { category: "一般動詞 (現在)", ja: "彼女は病院で働いています。", en: "She works at a hospital." },
    { category: "一般動詞 (現在)", ja: "彼は毎週日曜日にサッカーをします。", en: "He plays soccer every Sunday." },
    { category: "一般動詞 (現在)", ja: "私たちはすぐにあなたの助けが必要です。", en: "We need your help immediately." },
    { category: "一般動詞 (現在)", ja: "私の猫は一日中寝ています。", en: "My cat sleeps all day long." },
    { category: "一般動詞 (現在)", ja: "彼らは東京に住んでいます。", en: "They live in Tokyo." },
    { category: "一般動詞 (現在)", ja: "太陽は東から昇ります。", en: "The sun rises in the east." },
    { category: "一般動詞 (現在)", ja: "私はラグビーをしません。", en: "I do not play rugby." },
    { category: "一般動詞 (現在)", ja: "彼は納豆が好きではありません。", en: "He does not like natto." },
    { category: "一般動詞 (現在)", ja: "私たちはそのルールを理解していません。", en: "We do not understand the rule." },
    { category: "一般動詞 (現在)", ja: "あなたはラグビーが好きですか。", en: "Do you like rugby?" },
    { category: "一般動詞 (現在)", ja: "彼は熱心に英語を勉強しますか。", en: "Does he study English hard?" },
    { category: "一般動詞 (現在)", ja: "あなたは何を食べたいですか。", en: "What do you want to eat?" },
    { category: "一般動詞 (現在)", ja: "はい、好きです。", en: "Yes, I do." },
    { category: "一般動詞 (現在)", ja: "いいえ、好きではありません。", en: "No, he does not." },

    // --- 3. 一般動詞 (過去) ---
    { category: "一般動詞 (過去)", ja: "私は昨年の冬にカナダに滞在しました。", en: "I stayed in Canada last winter." },
    { category: "一般動詞 (過去)", ja: "私たちのチームは1位になりました。", en: "The team won first place." },
    { category: "一般動詞 (過去)", ja: "私はその日をとても楽しみました。", en: "I enjoyed that day very much." },
    { category: "一般動詞 (過去)", ja: "彼女は昨日、新しいドレスを買いました。", en: "She bought a new dress yesterday." },
    { category: "一般動詞 (過去)", ja: "私たちは2年前に京都を訪れました。", en: "We visited Kyoto two years ago." },
    { category: "一般動詞 (過去)", ja: "彼は簡単にその答えを見つけました。", en: "He found the answer easily." },
    { category: "一般動詞 (過去)", ja: "彼らはその計画について話し合いました。", en: "They talked about the plan." },
    { category: "一般動詞 (過去)", ja: "私は行商人の荷車から魚を取りました。", en: "I took some fish from a vendor's cart." },
    { category: "一般動詞 (過去)", ja: "私はお守りを買いませんでした。", en: "I did not buy a good luck charm." },
    { category: "一般動詞 (過去)", ja: "彼はパーティーに行きませんでした。", en: "He did not go to the party." },
    { category: "一般動詞 (過去)", ja: "彼女は私に真実を教えてくれませんでした。", en: "She did not tell me the truth." },
    { category: "一般動詞 (過去)", ja: "あなたはもちを食べましたか。", en: "Did you eat rice cakes?" },
    { category: "一般動詞 (過去)", ja: "彼女は宿題を終えましたか。", en: "Did she finish her homework?" },
    { category: "一般動詞 (過去)", ja: "昨晩、あなたは何をしましたか。", en: "What did you do last night?" },
    { category: "一般動詞 (過去)", ja: "はい、食べました。", en: "Yes, I did." },
    { category: "一般動詞 (過去)", ja: "いいえ、しませんでした。", en: "No, he did not." },

    // --- 4. 未来表現 (will / Be going to) ---
    { category: "未来表現", ja: "私は明日、シンガポールを訪れるつもりです。", en: "I am going to visit Singapore tomorrow." },
    { category: "未来表現", ja: "私が予約をしましょう。", en: "I will make a reservation." },
    { category: "未来表現", ja: "私があなたに何枚か写真を見せましょう。", en: "I will show you some pictures." },
    { category: "未来表現", ja: "彼女は来年、留学する予定です。", en: "She is going to study abroad next year." },
    { category: "未来表現", ja: "また近いうちにお会いしましょう。", en: "We will see you again soon." },
    { category: "未来表現", ja: "会議は10時に始まるでしょう。", en: "The meeting will start at ten." },
    { category: "未来表現", ja: "彼らは新しい道路を建設する予定です。", en: "They are going to build a new road." },
    { category: "未来表現", ja: "あなたの荷物を手伝いましょう。", en: "I'll help you with your baggage." },
    { category: "未来表現", ja: "私はそれを買うつもりはありません。", en: "I am not going to buy it." },
    { category: "未来表現", ja: "彼らはその計画に同意しないでしょう。", en: "They will not agree with the plan." },
    { category: "未来表現", ja: "彼女は学校に遅刻しないでしょう。", en: "She won't be late for school." },
    { category: "未来表現", ja: "あなたは明日、シンガポールを訪れるつもりですか。", en: "Are you going to visit Singapore tomorrow?" },
    { category: "未来表現", ja: "この箱を運ぶのを手伝ってくれませんか。", en: "Will you help me with this box?" },
    { category: "未来表現", ja: "私たちは空港のどこで会う予定ですか。", en: "Where are we going to meet in the airport?" },
    { category: "未来表現", ja: "はい、そのつもりです。", en: "Yes, I am." },
    { category: "未来表現", ja: "いいえ、しません。", en: "No, I will not." },

    // --- 5. 助動詞 (can/must/should/have to) ---
    { category: "助動詞", ja: "私はぎょうざを作ることができます。", en: "I can make gyoza." },
    { category: "助動詞", ja: "あなたは英語を話さなければなりません。", en: "You have to speak English." },
    { category: "助動詞", ja: "私たちは今、エネルギーを節約しなければなりません。", en: "We must save energy now." },
    { category: "助動詞", ja: "彼女は休むべきです。", en: "She should take a rest." },
    { category: "助動詞", ja: "私はその手紙を読むことができます。", en: "I can read that letter." },
    { category: "助動詞", ja: "彼らはルールに従わなければなりません。", en: "They have to follow the rules." },
    { category: "助動詞", ja: "あなたはここで電話を使ってはいけません。", en: "You must not use your phone here." },
    { category: "助動詞", ja: "私たちは先生の言うことを聞くべきです。", en: "We should listen to our teacher." },
    { category: "助動詞", ja: "私はシュウマイを作ることができません。", en: "I cannot make shumai." },
    { category: "助動詞", ja: "あなたは完璧な英語を話す必要はありません。", en: "You do not have to speak perfect English." },
    { category: "助動詞", ja: "彼女は一人で外出するべきではありません。", en: "She should not go out alone." },
    { category: "助動詞", ja: "あなたはひらがなを読むことができますか。", en: "Can you read hiragana?" },
    { category: "助動詞", ja: "私たちはこれを今日終えなければなりませんか。", en: "Do we have to finish this today?" },
    { category: "助動詞", ja: "私は今何をすべきですか。", en: "What should I do now?" },
    { category: "助動詞", ja: "はい、できます。", en: "Yes, I can." },
    { category: "助動詞", ja: "いいえ、できません。", en: "No, I cannot." },

    // --- 6. 不定詞 (名詞的/副詞的/形容詞的) ---
    { category: "不定詞", ja: "私は茶道部に入りたいです。", en: "I want to join the sado club!" },
    { category: "不定詞", ja: "私は英語を勉強するためにコンピュータを使います。", en: "I use a computer to study English." },
    { category: "不定詞", ja: "私はそれを聞いてうれしいです。", en: "I am happy to hear that." },
    { category: "不定詞", ja: "子供たちの顔を見ることが大切です。", en: "It is important to look at the children's faces." },
    { category: "不定詞", ja: "彼女にはするべき多くの仕事があります。", en: "She has a lot of work to do." },
    { category: "不定詞", ja: "私たちがこの問題を理解することが重要です。", en: "It is important for us to understand this problem." },
    { category: "不定詞", ja: "私の夢は世界中を旅することです。", en: "My dream is to travel the world." },
    { category: "不定詞", ja: "私は牛乳を買うために店に行きました。", en: "I went to the store to buy some milk." },
    { category: "不定詞", ja: "私は問題を起こしたくありません。", en: "I don't want to cause trouble." },
    { category: "不定詞", ja: "この問題を解決するのは簡単ではありません。", en: "It is not easy to solve this problem." },
    { category: "不定詞", ja: "私たちは今日読むものが何もありません。", en: "We have nothing to read today." },
    { category: "不定詞", ja: "あなたは何を食べたいですか。", en: "What do you want to eat?" },
    { category: "不定詞", ja: "何か言うことはありますか。", en: "Do you have anything to say?" },
    { category: "不定詞", ja: "今日、その仕事を終えることは可能ですか。", en: "Is it possible to finish the work today?" },
    { category: "不定詞", ja: "はい、私はチキンカレーを食べたいです。", en: "Yes, I want to eat chicken curry." },
    { category: "不定詞", ja: "いいえ、何も言うことはありません。", en: "No, I don't have anything to say." },

    // --- 7. 動名詞 ---
    { category: "動名詞", ja: "彼らは本を読むことを楽しみます。", en: "They enjoy reading books." },
    { category: "動名詞", ja: "彼と話すことは楽しかったです。", en: "Talking with him was fun." },
    { category: "動名詞", ja: "私の趣味は切手を集めることです。", en: "My hobby is collecting stamps." },
    { category: "動名詞", ja: "私は1年前に英語の勉強を始めました。", en: "I started studying English a year ago." },
    { category: "動名詞", ja: "彼は先月、喫煙をやめました。", en: "He gave up smoking last month." },
    { category: "動名詞", ja: "海外で暮らすことは素晴らしい経験です。", en: "Living abroad is a great experience." },
    { category: "動名詞", ja: "今日来てくれてありがとう。", en: "Thank you for coming today." },
    { category: "動名詞", ja: "百聞は一見に如かず（見ることが信じることだ）。", en: "Seeing is believing." },
    { category: "動名詞", ja: "私はしばらく待つことは気にしません。", en: "I don't mind waiting for a while." },
    { category: "動名詞", ja: "彼は彼女に話すのをやめました。", en: "He stopped talking to her." },
    { category: "動名詞", ja: "私は絵を描くのが得意ではありません。", en: "I am not good at drawing pictures." },
    { category: "動名詞", ja: "窓を開けてもよろしいですか。", en: "Do you mind opening the window?" },
    { category: "動名詞", ja: "歴史を学ぶことは重要ですか。", en: "Is learning history important?" },
    { category: "動名詞", ja: "あなたは何をすることに興味がありますか。", en: "What are you interested in doing?" },
    { category: "動名詞", ja: "はい、ビデオゲームをすることを楽しんでいます。", en: "Yes, I enjoy playing video games." },
    { category: "動名詞", ja: "いいえ、開けても構いません。", en: "No, I don't mind opening it." },

    // --- 8. 現在進行形・過去進行形 ---
    { category: "進行形", ja: "私は今、テレビを見ています。", en: "I am watching TV now." },
    { category: "進行形", ja: "私はそのときサッカーをしていました。", en: "I was playing soccer then." },
    { category: "進行形", ja: "彼女は電話で話しています。", en: "She is talking on the phone." },
    { category: "進行形", ja: "彼が入ってきたとき、私たちは勉強していました。", en: "We were studying when he came in." },
    { category: "進行形", ja: "彼らは図書館に向かって歩いています。", en: "They are walking to the library." },
    { category: "進行形", ja: "ちょうど今、外は雨が降っています。", en: "It is raining outside right now." },
    { category: "進行形", ja: "私が彼に電話したとき、彼は寝ていました。", en: "He was sleeping when I called him." },
    { category: "進行形", ja: "私は顧客にEメールを書いています。", en: "I am writing an email to my client." },
    { category: "進行形", ja: "私は今、昼食を食べていません。", en: "I am not having lunch now." },
    { category: "進行形", ja: "彼女は全く私の話を聞いていませんでした。", en: "She was not listening to me at all." },
    { category: "進行形", ja: "彼らはパーティーに来ません。", en: "They are not coming to the party." },
    { category: "進行形", ja: "あなたは本を読んでいますか。", en: "Are you reading a book?" },
    { category: "進行形", ja: "あなたはコンテストの最中に緊張していましたか。", en: "Were you nervous during the contest?" },
    { category: "進行形", ja: "あなたは何を探していますか。", en: "What are you looking for?" },
    { category: "進行形", ja: "はい、していました。", en: "Yes, I was." },
    { category: "進行形", ja: "いいえ、していません。", en: "No, I am not." },

    // --- 9. 現在完了 (経験・完了・継続) ---
    { category: "現在完了", ja: "私は日本のアニメを2回見たことがあります。", en: "I have watched Japanese anime twice." },
    { category: "現在完了", ja: "私は5年間ずっと日本に住んでいます。", en: "I have lived in Japan for five years." },
    { category: "現在完了", ja: "私はちょうど宿題を終えたところです。", en: "I have just finished my homework." },
    { category: "現在完了", ja: "私は午後4時からずっと本を読んでいます。", en: "I have been reading a book since 4 p.m." },
    { category: "現在完了", ja: "彼女は京都に何度も行ったことがあります。", en: "She has visited Kyoto many times." },
    { category: "現在完了", ja: "私たちはすでにもう昼食を食べました。", en: "We have already eaten lunch." },
    { category: "現在完了", ja: "彼は2020年からここで働いています。", en: "He has worked here since 2020." },
    { category: "現在完了", ja: "彼らは長い間お互いを知っています。", en: "They have known each other for a long time." },
    { category: "現在完了", ja: "エディは日本のアニメを一度も見たことがありません。", en: "Eddy has never watched Japanese anime." },
    { category: "現在完了", ja: "私は最近彼に会っていません。", en: "I have not seen him recently." },
    { category: "現在完了", ja: "彼女はまだその美術館に行ったことがありません。", en: "She hasn't been to that museum yet." },
    { category: "現在完了", ja: "あなたはこれまでにアニメのイベントに行ったことがありますか。", en: "Have you ever been to an anime event?" },
    { category: "現在完了", ja: "あなたはもう宿題を終えましたか。", en: "Have you finished your homework yet?" },
    { category: "現在完了", ja: "あなたはどのくらい長く日本に住んでいますか。", en: "How long have you lived in Japan?" },
    { category: "現在完了", ja: "はい。私はすでにそれを終えました。", en: "Yes, I have. I have already finished it." },
    { category: "現在完了", ja: "いいえ、ありません。私は一度も行ったことがありません。", en: "No, I have not. I have never been to one." },

    // --- 10. 受動態 ---
    { category: "受動態", ja: "タージ・マハルは多くの人々に愛されています。", en: "The Taj Mahal is loved by many people." },
    { category: "受動態", ja: "この場所は世界遺産に選ばれています。", en: "This place is selected as a World Heritage site." },
    { category: "受動態", ja: "富士山は永遠に人々に楽しまれるでしょう。", en: "Mt. Fuji will be enjoyed by people forever." },
    { category: "受動態", ja: "それはケープ植物区と呼ばれています。", en: "It is called the Cape Floral Region." },
    { category: "受動態", ja: "英語は多くの国で話されています。", en: "English is spoken in many countries." },
    { category: "受動態", ja: "コンピュータは20世紀に発明されました。", en: "The computer was invented in the 20th century." },
    { category: "受動態", ja: "この歌は有名な音楽家によって書かれました。", en: "This song was written by a famous musician." },
    { category: "受動態", ja: "その橋は最近、再建されました。", en: "The bridge has been rebuilt recently." },
    { category: "受動態", ja: "その城は多くの観光客には訪れられません。", en: "The castle is not visited by many tourists." },
    { category: "受動態", ja: "その書類は昨日、配達されませんでした。", en: "The paper was not delivered yesterday." },
    { category: "受動態", ja: "その門は簡単には開けられません。", en: "The gate cannot be opened easily." },
    { category: "受動態", ja: "それはケープ植物区と呼ばれていますか。", en: "Is it called the Cape Floral Region?" },
    { category: "受動態", ja: "その窓は風によって割られましたか。", en: "Was the window broken by the wind?" },
    { category: "受動態", ja: "誰によってその手紙は書かれましたか。", en: "By whom was the letter written?" },
    { category: "受動態", ja: "はい、呼ばれています。", en: "Yes, it is." },
    { category: "受動態", ja: "いいえ、そうではありませんでした。", en: "No, it was not." },

    // --- 11. 比較 (原級・比較級・最上級) ---
    { category: "比較", ja: "サッカーはテニスと同じくらい人気があります。", en: "Soccer is as popular as tennis." },
    { category: "比較", ja: "このスポーツはあのスポーツよりもおもしろいです。", en: "This sport is more interesting than that one." },
    { category: "比較", ja: "このスポーツは全ての中でいちばんおもしろいです。", en: "This sport is the most interesting sport of all." },
    { category: "比較", ja: "グレートバリアリーフはアマゾン熱帯雨林よりも小さいです。", en: "The Great Barrier Reef is smaller than the Amazon rainforest." },
    { category: "比較", ja: "彼女は私よりも速く走ります。", en: "She runs faster than I do." },
    { category: "比較", ja: "この箱は3つの中でいちばん重いです。", en: "This box is the heaviest of the three." },
    { category: "比較", ja: "彼は彼の兄と同じくらい多くの本を持っています。", en: "He has as many books as his brother." },
    { category: "比較", ja: "地球は月よりずっと大きいです。", en: "The Earth is much bigger than the moon." },
    { category: "比較", ja: "このホテルは私が思っていたほど高くありません。", en: "This hotel is not as expensive as I thought." },
    { category: "比較", ja: "彼は彼女ほど一生懸命には働きません。", en: "He doesn't work as hard as she does." },
    { category: "比較", ja: "冬はここでの最も寒い季節ではありません。", en: "Winter is not the coldest season here." },
    { category: "比較", ja: "英語は数学と同じくらい重要ですか。", en: "Is English as important as math?" },
    { category: "比較", ja: "都市と町、どちらが大きいですか。", en: "Which is larger, the city or the town?" },
    { category: "比較", ja: "あなたのクラスで一番背が高いのは誰ですか。", en: "Who is the tallest person in your class?" },
    { category: "比較", ja: "はい、サッカーはテニスと同じくらい人気があります。", en: "Yes, soccer is as popular as tennis." },
    { category: "比較", ja: "都市の方が大きいです。", en: "The city is larger." },

    // --- 12. 関係代名詞 (主格・目的格・分詞の後置修飾) ---
    { category: "関係代名詞", ja: "ガンディーは多くの人々に影響を与えた人です。", en: "Gandhi is a man who has influenced a lot of people." },
    { category: "関係代名詞", ja: "これは人々を幸せにする映画です。", en: "This is a movie that makes people happy." },
    { category: "関係代名詞", ja: "これは私がインターネットで見つけた写真です。", en: "This is a picture I found on the internet." },
    { category: "関係代名詞", ja: "私たちが毎日目にする多くのものは海外から来ています。", en: "Many things that we see every day come from overseas." },
    { category: "関係代名詞", ja: "着物を着てほほえんでいる女性はテイラーです。", en: "The woman smiling in a kimono is Taylor." },
    { category: "関係代名詞", ja: "私は英語で書かれた本を買いました。", en: "I bought a book which was written in English." },
    { category: "関係代名詞", ja: "私が最も欲しいものは平和です。", en: "What I want most is peace." },
    { category: "関係代名詞", ja: "私はよく医者である母と話します。", en: "I often talk with my mother, who is a doctor." },
    { category: "関係代名詞", ja: "私はあそこに立っている男性を知りません。", en: "I don't know the man who is standing over there." },
    { category: "関係代名詞", ja: "これは私が期待した結果ではありません。", en: "This is not the result I expected." },
    { category: "関係代名詞", ja: "署名されていなかった手紙は怪しいです。", en: "The letter which was not signed is suspicious." },
    { category: "関係代名詞", ja: "部に入った女の子の名前は何ですか。", en: "What is the name of the girl who joined the club?" },
    { category: "関係代名詞", ja: "昨日私がなくした鍵を見つけましたか。", en: "Did you find the key I lost yesterday?" },
    { category: "関係代名詞", ja: "彼が言ったことについてどう思いますか。", en: "What do you think about the things he said?" },
    { category: "関係代名詞", ja: "はい、それが賞を取った本です。", en: "Yes, that is the book which won the prize." },
    { category: "関係代名詞", ja: "いいえ、あなたがなくした鍵は見つけませんでした。", en: "No, I didn't find the key you lost." },

    // --- 13. There is/are ---
    { category: "There is/are", ja: "湖の近くにキャンプ場があります。", en: "There is a campground near the lake." },
    { category: "There is/are", ja: "『夢を生きる』と呼ばれる映画があります。", en: "There is a movie called Live Your Dream." },
    { category: "There is/are", ja: "公園にはたくさんの木があります。", en: "There are many trees in the park." },
    { category: "There is/are", ja: "広場には大きな群衆がいました。", en: "There was a large crowd in the square." },
    { category: "There is/are", ja: "来週、コンサートがあるでしょう。", en: "There will be a concert next week." },
    { category: "There is/are", ja: "話し合うべき重要なことが何かあります。", en: "There is something important to discuss." },
    { category: "There is/are", ja: "私のクラスには2人の新しい生徒がいます。", en: "There are two new students in my class." },
    { category: "There is/are", ja: "道路で事故がありました。", en: "There has been an accident on the road." },
    { category: "There is/are", ja: "残された時間は十分ではありません。", en: "There is not enough time left." },
    { category: "There is/are", ja: "真夜中以降は電車がありません。", en: "There are no trains after midnight." },
    { category: "There is/are", ja: "その結果に問題はありませんでした。", en: "There wasn't a problem with the result." },
    { category: "There is/are", ja: "湖の近くにキャンプ場がありますか。", en: "Is there a campground near the lake?" },
    { category: "There is/are", ja: "何か質問はありますか。", en: "Are there any questions?" },
    { category: "There is/are", ja: "その箱の中には何がありますか。", en: "What is there in the box?" },
    { category: "There is/are", ja: "はい、あります。", en: "Yes, there is." },
    { category: "There is/are", ja: "いいえ、ありません。", en: "No, there are not." },

    // --- 14. 仮定法 (過去 / I wish) ---
    { category: "仮定法", ja: "学校に行くことができればいいのになあ。", en: "I wish I could go to school." },
    { category: "仮定法", ja: "もし私があなたなら、友達に助けを求めるでしょう。", en: "If I were you, I would ask my friends for help." },
    { category: "仮定法", ja: "もし私がランドセルを持っていれば、寄付するでしょう。", en: "If I had a school backpack, I would donate it." },
    { category: "仮定法", ja: "その答えを知っていればいいのになあ。", en: "I wish I knew the answer." },
    { category: "仮定法", ja: "もし晴れていたら、ハイキングに行けるのに。", en: "If it were sunny, we could go hiking." },
    { category: "仮定法", ja: "彼はまるでプロであるかのように話します。", en: "He talks as if he were a professional." },
    { category: "仮定法", ja: "もし私がフランス語を話せたら、パリに住むだろう。", en: "If I spoke French, I would live in Paris." },
    { category: "仮定法", ja: "飛べたらいいのになあ。", en: "I wish I could fly." },
    { category: "仮定法", ja: "もし彼女がそんなに忙しくなければ、来るだろうに。", en: "If she weren't so busy, she would come." },
    { category: "仮定法", ja: "今週末、仕事をしなければならなければいいのに。", en: "I wish I didn't have to work this weekend." },
    { category: "仮定法", ja: "もし電車に乗り遅れていなかったら、遅刻しないだろうに。", en: "If I hadn't missed the train, I wouldn't be late." },
    { category: "仮定法", ja: "もしあなたが私だったら、何をしますか。", en: "What would you do if you were me?" },
    { category: "仮定法", ja: "もし時間があったら、私を手伝ってくれますか。", en: "Would you help me if you had time?" },
    { category: "仮定法", ja: "もしあなたが仕事を変えるとしたら、何を選びますか。", en: "If you were to change your job, what would you choose?" },
    { category: "仮定法", ja: "はい、もし私があなたなら、助けを求めるでしょう。", en: "Yes, if I were you, I would ask for help." },
    { category: "仮定法", ja: "いいえ、もし私があなたでも仕事は変えないでしょう。", en: "No, I would not change my job if I were you." }
];