const allQuizData = [
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "私はエドワード・トラウトです。", en: "I am Edward Trout." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "あなたはアニメのファンですか。", en: "Are you an anime fan?" },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "勇気を出して。", en: "Be brave." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "心配しないで。", en: "Don't worry." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "子供たちは幸せそうに見えます。", en: "The children look happy." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "彼と話すことは楽しかったです。", en: "Talking with him was fun." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "私の姉は歌が上手です。", en: "My sister sings well." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "空は青いです。", en: "The sky is blue." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "彼女は先生になりました。", en: "She became a teacher." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "私たちは一生懸命働きます。", en: "We work hard." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "ドアが開きました。", en: "The door opened." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "その食べ物は塩辛い味がします。", en: "The food tastes salty." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "みんなが微笑みました。", en: "Everyone smiled." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "赤ちゃんは眠っています。", en: "The baby is sleeping." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "私は今日気分がいいです。", en: "I feel fine today." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "彼は辛抱強く待ちました。", en: "He waited patiently." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "どうぞお座りください。", en: "Please sit down." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "この計画は素晴らしそうです。", en: "This plan sounds great." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "コンサートは9時に終わりました。", en: "The concert ended at nine." },
    { category: "パターン 1: 誰が(S) する(V) (S+V/S+V+C)", ja: "外は雪が降っています。", en: "It is snowing outside." },
            
    // パターン 2: 誰が(S) する(V) 何を(O) (S+V+O) (20問)
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私は日本の甘い菓子が好きです。", en: "I like Japanese sweets." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私はぎょうざを作ることができます。", en: "I can make gyoza." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私が予約をしましょう。", en: "I will make a reservation." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "あなたは英語を話さなければなりません。", en: "You have to speak English." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼らは本を読むことを楽しみます。", en: "They enjoy reading books." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼女は困っている人々を助けたいと思っています。", en: "She wants to help people in need." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私たちは新しい自転車を買いました。", en: "We bought a new bicycle." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私はその答えを知りません。", en: "I don't know the answer." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "あなたはそのニュースを見ましたか。", en: "Did you see the news?" },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼は宿題を終えるべきです。", en: "He should finish his homework." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私は財布をなくしてしまいました。", en: "I have lost my wallet." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼女はいくつか助言が必要です。", en: "She needs some advice." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "その問題について話し合いましょう。", en: "Let's discuss the problem." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "そのチームは試合に勝ちました。", en: "The team won the game." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私は家族を守らなければなりません。", en: "I must protect my family." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私たちは美術館を訪れるつもりです。", en: "We are going to visit the museum." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "どうぞ電気を消してください。", en: "Please turn off the light." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼はその電車に乗り遅れました。", en: "He missed the train." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "私はよくアメリカ映画を見ます。", en: "I often watch American movies." },
    { category: "パターン 2: 誰が(S) する(V) 何を(O) (S+V+O)", ja: "彼らは政治について話すのを避けました。", en: "They avoided talking about politics." },

            
    // パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O) (20問)
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私があなたに何枚か写真を見せましょう。", en: "I will show you some pictures." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "ラッコについて伝えさせてください。", en: "Let us tell you about sea otters." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "その話は私にどんなことでも可能だということを示してくれます。", en: "The story shows me that anything is possible." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私の父は私に新しい腕時計をくれました。", en: "My father gave me a new watch." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私にペンを貸してくれますか。", en: "Can you lend me a pen?" },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私は彼にコーヒーを一杯買いました。", en: "I bought him a cup of coffee." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼女は私たちに英語を教えました。", en: "She taught us English." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "どうぞ私に塩を取ってください。", en: "Please pass me the salt." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私は先生にEメールを送りました。", en: "I sent an email to my teacher." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼は私たちにルールを説明しました。", en: "He explained the rule to us." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼らは彼女に良い仕事を提案しました。", en: "They offered her a good job." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私は母にケーキを作りました。", en: "I made a cake for my mother." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "この手紙を私に読んでくれますか。", en: "Will you read me this letter?" },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼女は娘に旅行を約束しました。", en: "She promised her daughter a trip." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "あなたに紅茶を持ってきましょう。", en: "I will bring you some tea." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "スタッフにあなたのチケットを見せてください。", en: "Show your ticket to the staff." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼らは私に難しい質問をしました。", en: "They asked me a difficult question." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私たちはゲストのために席を取っておかねばなりません。", en: "We must save seats for our guests." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "私にあなたのフルネームを教えてください。", en: "Tell me your full name." },
    { category: "パターン 3: 誰が(S) する(V) 誰に(O) 何を(O) (S+V+O+O)", ja: "彼は友達のためにいい場所を見つけました。", en: "He found a nice spot for his friends." },
   

    // パターン 4: 誰が(S) する(V) 何を(O) どんな状態に(C) (S+V+O+C) (20問)
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "人々はこの区域をリトル・インディアと呼びます。", en: "People call this area Little India." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "アニメソングは私を幸せにします。", en: "Anime songs make me happy." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私は全ての人にこの問題を知ってほしいです。", en: "I want everyone to know about this problem." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私たちはその箱が空だと分かりました。", en: "We found the box empty." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "彼らは娘をサクラと名付けました。", en: "They named their daughter Sakura." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "その知らせは私たちを悲しませました。", en: "The news made us sad." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "彼は部屋をきれいに保ちました。", en: "He kept the room clean." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私は彼に謝ってほしいです。", en: "I want him to apologize." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "先生は私たちに本を開くように言いました。", en: "My teacher told us to open our books." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "明るい太陽が葉を黄色に変えました。", en: "The bright sun turned the leaves yellow." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私たちは彼が正直だと信じています。", en: "We believe him honest." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "彼らは彼女を大統領に選びました。", en: "They elected her president." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "ドアの鍵を開けたままにしないでください。", en: "Don't leave the door unlocked." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私は彼が逃げ去るのを見ました。", en: "I saw him running away." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私たちはその結果を驚くべきものだと思います。", en: "We think the result amazing." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "彼らは壁を緑色に塗りました。", en: "They painted the wall green." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私は自分の名前が呼ばれるのを聞きました。", en: "I heard my name called." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "医者は彼に休むように忠告しました。", en: "The doctor advised him to rest." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "彼女はウェイターに勘定書きを持ってこさせました。", en: "She had the waiter bring the check." },
    { category: "パターン 4: 誰が(S) する(V) 何を(O) と呼ぶ(C) (S+V+O+C)", ja: "私はこの点が重要だと考えます。", en: "I consider this point important." },
 

    // パターン 5: 誰が(S) する(V) どこで(M) いつ(T) なぜ(R) (S+V+MTR) (20問)
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "文也はハワイに住んでいます。", en: "Fumiya lives in Hawaii." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は月曜日に学校に来ます。", en: "I come to school on Mondays." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は昨年の冬にカナダに滞在しました。", en: "I stayed in Canada last winter." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は今、テレビを見ています。", en: "I am watching TV now." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は5年間ずっと日本に住んでいます。", en: "I have lived in Japan for five years." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私はラーメン店に行くとき、豚骨ラーメンを注文します。", en: "When I go to a ramen restaurant, I order tonkotsu ramen." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "もし時間があれば、あなたは来ることができます。", en: "If you have time, you can come." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私たちは昨日、家で夕食を食べました。", en: "We had dinner at home yesterday." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "彼はとても速く走ります。", en: "He runs very fast." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "彼女は毎日英語を勉強します。", en: "She studies English every day." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "彼らは駅に遅れて到着しました。", en: "They arrived at the station late." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は放課後あなたに電話します。", en: "I will call you after school." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私たちは今年の夏、ビーチに行くつもりです。", en: "We are going to the beach this summer." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "会議は一番大きな部屋で開かれました。", en: "The meeting was held in the biggest room." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "彼女はいつも丁寧に話します。", en: "She always speaks politely." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "あなたはマニュアルを注意深く読むべきです。", en: "You should read the manual carefully." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "電車が遅れたので、私は遅刻しました。", en: "Because the train was delayed, I was late." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は椅子のもとで鍵を見つけました。", en: "I found my key under the chair." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "彼は簡単にその仕事を終えました。", en: "He finished the work easily." },
    { category: "パターン 5: どこ(A) いつ(A) など (修飾語)", ja: "私は月に2回、祖父母を訪ねます。", en: "I visit my grandparents twice a month." },
    

    // パターン 6: 誰が(S) する(V) 何を(O) どこで(M) いつ(T) なぜ(R) (S+V+O+MTR) (20問)
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "子供たちの顔を見ることが大切です。", en: "It is important to look at the children's faces." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼女にはするべき多くの仕事があります。", en: "She has a lot of work to do." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私は英語を勉強するためにコンピュータを使います。", en: "I use a computer to study English." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私はそれを聞いてうれしいです。", en: "I am happy to hear that." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私たちがこの問題を理解することが重要です。", en: "It is important for us to understand this problem." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼らは本を読むことを楽しみます。", en: "They enjoy reading books." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼と話すことは楽しかったです。", en: "Talking with him was fun." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "はっきりと話すことが私の目標です。", en: "To speak clearly is my goal." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私は新しいカフェを試すことを決めました。", en: "I decided to try the new cafe." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私たちは休憩するために公園に行きました。", en: "We went to the park to take a rest." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼はその損害を見て驚きました。", en: "He was surprised to see the damage." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "それらの言葉を覚えるのは簡単です。", en: "It is easy to remember those words." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私たちを助けてくれるなんて、あなたは親切です。", en: "It is kind of you to help us." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私は何か冷たい飲み物がほしいです。", en: "I want something cold to drink." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私の仕事は顧客を助けることです。", en: "My job is to help customers." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼は忙しすぎて会議に参加できません。", en: "He is too busy to join the meeting." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "全員がルールに従うことが必要です。", en: "It is necessary for everyone to follow the rules." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "汚染を止めることは未来にとって不可欠です。", en: "Stopping pollution is essential for the future." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "私は長時間待つことは気にしません。", en: "I don't mind waiting for a long time." },
    { category: "パターン 6: 複雑なSやOを作る名詞構造", ja: "彼の夢は世界中を旅することです。", en: "His dream is traveling around the world." },
    

    // パターン 7: S+V+O+O+MTR (20問)
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "ガンディーは多くの人々に影響を与えた人です。", en: "Gandhi is a man who has influenced a lot of people." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "これは人々を幸せにする映画です。", en: "This is a movie that makes people happy." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "これは私がインターネットで見つけた写真です。", en: "This is a picture I found on the internet." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私たちが毎日目にする多くのものは海外から来ています。", en: "Many things that we see every day come from overseas." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "着物を着てほほえんでいる女性はテイラーです。", en: "The woman smiling in a kimono is Taylor." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "彼女にはロンドンに住んでいる友達がいます。", en: "She has a friend who lives in London." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "故障した車はとても古かったです。", en: "The car that broke down was very old." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私はあなたが推薦した本を読みました。", en: "I read the book that you recommended." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "これが両親から受け取ったプレゼントです。", en: "This is the gift I received from my parents." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "電話で話している男性がマネージャーです。", en: "The man talking on the phone is the manager." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私たちは1900年に建てられた美術館を訪れました。", en: "We visited the museum built in 1900." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私たちが会った場所の名前を思い出せません。", en: "I can't remember the name of the place where we met." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "彼がやめた理由を知っていますか。", en: "Do you know the reason why he quit?" },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "あなたがその問題を解決した方法を教えてください。", en: "Tell me the way you solved the problem." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私は仕事が私と似ている人が必要です。", en: "I need a person whose job is similar to mine." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私が最も欲しいものは平和です。", en: "What I want most is peace." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "この問題についてあなたがどう思うか教えてください。", en: "Please tell me what you think about this issue." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "守らなければならないルールは単純です。", en: "The rule which must be obeyed is simple." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "彼によって撮られた写真を見てください。", en: "Look at the pictures taken by him." },
    { category: "パターン 7: 名詞を説明する(関係代名詞など)", ja: "私はよく医者である母と話します。", en: "I often talk with my mother, who is a doctor." },
    

    // パターン 8: S+V+O+C+MTR (20問)
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "タージ・マハルは多くの人々に愛されています。", en: "The Taj Mahal is loved by many people." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "富士山は永遠に人々に楽しまれるでしょう。", en: "Mt. Fuji will be enjoyed by people forever." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "湖の近くにキャンプ場があります。", en: "There is a campground near the lake." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "Live Your Dreamと呼ばれる映画があります。", en: "There is a movie called Live Your Dream." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "この建物は1950年に建てられました。", en: "This building was built in 1950." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "英語は多くの国で話されています。", en: "English is spoken in many countries." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "その報告書は明日までに終えられなければなりません。", en: "The report must be finished by tomorrow." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "その窓は風によって割られましたか。", en: "Was the window broken by the wind?" },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "私はその知らせに驚きました。", en: "I was surprised at the news." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "その本は何百万もの人々に読まれてきました。", en: "The book has been read by millions." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "私の自転車は今、修理されているところです。", en: "My bike is being fixed now." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "この通りには2軒のコーヒーショップがあります。", en: "There are two coffee shops on this street." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "広場には大きな群衆がいました。", en: "There was a large crowd in the square." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "新しい美術館は来月開館するでしょう。", en: "The new museum will be opened next month." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "そのスタジアムは世界中で知られています。", en: "The stadium is known all over the world." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "その事故は人為的なミスによって引き起こされました。", en: "The accident was caused by human error." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "来週、公園でコンサートがあるでしょう。", en: "There will be a concert in the park next week." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "その箱は古い写真でいっぱいでした。", en: "The box was filled with old pictures." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "このシステムによって多くエネルギーが節約されます。", en: "A lot of energy is saved by this system." },
    { category: "パターン 8: 特殊な構文 (受動態, There is)", ja: "私の答えに何か間違いはありますか。", en: "Is there anything wrong with my answer?" },
    

    // パターン 9: 準動詞 (20問)
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "学校に行くことができればいいのになあ。", en: "I wish I could go to school." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私があなたなら、友達に助けを求めるでしょう。", en: "If I were you, I would ask my friends for help." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私がランドセルを持っていれば、寄付するでしょう。", en: "If I had a school backpack, I would donate it." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もっと読書する時間があればいいのになあ。", en: "I wish I had more time to read." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私が動物なら、イルカになるでしょう。", en: "If I were an animal, I would be a dolphin." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし彼女がここにいれば、何をすべきかわかるだろうに。", en: "If she were here, she would know what to do." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "彼はまるでリーダーであるかのように振る舞います。", en: "He acts as if he were a leader." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし晴れていたら、ハイキングに行けるのに。", en: "If it were sunny, we could go hiking." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "今週末、仕事をしなくて済めばいいのに。", en: "I wish I didn't have to work this weekend." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし宝くじに当たったら、何をしますか。", en: "What would you do if you won the lottery?" },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし彼らがルールを変えたら、試合はもっとよくなるだろうに。", en: "If they changed the rule, the game would be better." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "あの質問の答えを知っていればいいのに。", en: "I wish I knew the answer to that question." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私がフランス語を話せたら、パリに住めるのに。", en: "If I spoke French, I could live in Paris." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "彼女はまるで数日間寝ていないかのように見えました。", en: "She looked as if she hadn't slept for days." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "月に飛んで行けたらいいのになあ。", en: "I wish I could fly to the moon." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もしもっと一生懸命勉強していたら、試験に合格していただろうに。", en: "If I had studied harder, I would have passed the exam." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私が医者になったら、困っている人々を助けるだろう。", en: "If I became a doctor, I would help people in need." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もしこの方法を試したら、あなたはより良い結果を得られるでしょう。", en: "You could get better results if you tried this method." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "あの言葉を言わなければよかったのに。", en: "I wish I hadn't said those words." },
    { category: "パターン 9: 可能性や願望を表現する仮定法", ja: "もし私たちが一緒に働けば、もっと早く終わるだろう。", en: "If we worked together, we would finish faster." }
];